// Tempest.Launcher/src/components/layout/Header.vue
<script setup lang="ts">
const { text } = defineProps<{
    text: string
}>();
</script>

<template>
	<header>
        <h1>{{ text }}</h1>
		<section>
            <slot />
        </section>
	</header>
</template>

<style scoped>
header {
    display: flex;
    justify-content: space-between;
    align-items: center;
}

h1 {
    font-weight: 900;
    text-shadow: var(--c-black) 2px 2px 4px;
}

section {
    display: flex;
    align-items: center;
    gap: 1rem;
}
</style>

// Tempest.Launcher/src/lib/components/layout/Header.svelte
<script>
	import Button from "$lib/components/ui/Button.svelte";

</script>
<header class="header">
	<div class="section">
		<Button icon>{"<"}</Button>
		<Button icon>{">"}</Button>
	</div>
	<div class="section">right</div>
</header>

<style>
	.header {
		background-color: var(--bg-surface);
		padding: 0 var(--spacing-lg);
		min-height: 4rem;
		justify-content: space-between;
		width: 100vw;
	}

	.section {
		gap: var(--spacing-sm);
	}

	.header, .section {
		display: flex;
		align-items: center;
	}
</style>
