// Tempest.Launcher/src/lib/components/layout/Header.svelte
<script>
	import Button from "$lib/components/ui/Button.svelte";

</script>
<header class="header">
	<div class="section">
		<Button icon>{"<"}</Button>
		<Button icon>{">"}</Button>
	</div>
	<div class="section">right</div>
</header>

<style>
	.header {
		background-color: var(--bg-surface);
		padding: 0 var(--spacing-lg);
		min-height: 4rem;
		justify-content: space-between;
		width: 100vw;
	}

	.section {
		gap: var(--spacing-sm);
	}

	.header, .section {
		display: flex;
		align-items: center;
	}
</style>

// Tempest.Launcher/src/components/ui/Navigation/Header.vue
<template>
	<p>
		<slot />
	</p>
</template>

<style scoped>
p {
	color: var(--c-text-1);
	font-weight: 900;
	font-size: 1.4rem;
	padding: 0 2rem;
	height: 100%;
	display: flex;
	align-items: center;
	justify-content: center;
	text-decoration: none;
	text-shadow: var(--c-black) 2px 2px 4px;
}
</style>
